services:
  web:
    image: nginx:alpine
    container_name: chidole
    restart: unless-stopped
    ports:
      - "8181:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
